# Generated by Django 5.2.4 on 2025-08-19 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_shop_advert_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='sellers.shop'),
            preserve_default=False,
        ),
    ]
