# Generated by Django 5.2.4 on 2025-08-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_advert_shape_advert_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rank',
            field=models.CharField(choices=[('hustler', 'Hustler'), ('verified', 'Verified'), ('pro', 'Pro')], default='hustler', max_length=20),
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shops/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sellers.shop')),
            ],
        ),
    ]
