# Generated by Django 5.2.4 on 2025-08-25 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_shop_rank_shopimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='shops/banners/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='delivery_areas',
            field=models.TextField(blank=True, help_text='List of areas served (comma separated)', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='delivery_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shops/logos/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='notify_on_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='payment_number',
            field=models.CharField(blank=True, help_text='Mpesa / Mobile Money', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='refund_policy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
