# Generated by Django 5.2.4 on 2025-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_shop_active_shop_address_shop_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='attributes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
