# Generated by Django 5.2.4 on 2025-08-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_advert_active_advert_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variants/')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sellers.advert')),
            ],
        ),
    ]
