# Generated by Django 5.2.4 on 2025-10-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_review_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
